### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by CriziiTV** [ic3d00/ic3d_vendingmachines#2]
hey thx for your nice script

to give something back here is the german tranlation

Locales["de"] = {
  ["nearprop"] = "Drücke ~g~[E] ~c~, um an den Automaten zu gehen",
  ["bought"] = "Du hast %sx %s für ~r~$%s gekauft",
  ["not_enough"] = "Du hast nicht genug Geld, es fehlt dir ~r~$%s",
  ["player_cannot_hold"] = "Du hast nicht genug Platz in deinem Inventar!"
}

**Comment by ic3d00** [comment]
Hey, thank you!
If you can, please open a [PR](https://github.com/ic3d00/ic3d_vendingmachines/compare) including that!

Thanks again!

**Comment by ic3d00** [comment]
Btw, It will improve your github activity and include you as a contributor for the script.

**Comment by CriziiTV** [comment]
Hey im new to all of this. i dont know how to open a pull request. it dont let me create a pull request and i dont know why...

**Comment by ic3d00** [comment]
![image](https://github.com/ic3d00/ic3d_vendingmachines/assets/65400214/2d637250-d346-41d4-9234-516965ec27d7)

Now create your file and it will make a fork, then, you can make a pull request.

**Comment by CriziiTV** [comment]
ah thx

**Comment by CriziiTV** [comment]
nice thx for teaching  me
